name: Checks

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: ./gradlew test

      - name: Detekt
        run: ./gradlew detekt
